---
title: "Sales location analysis"
author: "Ian Thulin"
date: "2023-05-11"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r install packages, include=FALSE,eval=FALSE}
packages_to_install <- c("tidygeocoder",
                         "readxl",
                         "stringer",
                         "tidyr",
                         "dplyr",
                         "ggplot2",
                         "viridis",
                         "ggpointdensity",
                         "usmap",
                         "maptools",
                         "rgdal",
                         "ggmap",
                         "lubridate",
                         "vtable",
                         "psych")
not_installed <- packages_to_install[!(packages_to_install %in% installed.packages()[ , "Package"])]
if(length(not_installed)) install.packages(not_installed)
```

```{r load packages, include=FALSE}
library(ggplot2)
library("tidygeocoder")
library(readxl)
library(dplyr)
library(stringr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(viridis)
library(ggpointdensity)
library(usmap)
library(maptools)
library(rgdal)
library(ggmap)
library(lubridate)
library(vtable)
library(psych)
source("https://raw.githubusercontent.com/iascchen/VisHealth/master/R/calendarHeat.R")
source("https://raw.githubusercontent.com/iascchen/VisHealth/master/R/calendarHeat.R")
```

```{r data folder creation}
if(!file.exists("Data")){dir.create("Data")}
```

```{r clean the address data}
if(!file.exists("Data/Raw data (pre-geocoding).csv")) {

# Load in the original data files
Raw_sales_data <- read_excel("Data/Sandia Sunrooms - Sales Data - Lead Perfection - 5.11.2023.xlsx")
Raw_prospect_data <- read_excel("Data/Sandia Sunrooms - Prospect Data - Lead Perfection - 5.11.2023.xlsx")

# We need to remove several fields from the given data set to protect the anonymity of our clients
Raw_sales_data <- Raw_sales_data %>% select(-FirstName, -LastName, -Phone, -Phone2)
Raw_prospect_data <- Raw_prospect_data %>% rename("id" = "CustNumber",
                                                  "productid" = "Productid",
                                                  "SubSource" = "SourceSubDescr")
Raw_prospect_data$id <- as.numeric(as.character(Raw_prospect_data$id))

# Combine the two data sets into a single data frame consisting of all sales and prospect information
Raw_data <- dplyr::bind_rows(Raw_sales_data, Raw_prospect_data)
  # Convert the address column to upper case to help type and direction recognition
Raw_data$Address1 <- toupper(Raw_data$Address1)

# Regular expression for each component we need to strip
number_regex <- "^\\d+"
street_regex <- "\\b[A-Za-z]+(\\s+(?!ST|AVE|BLVD|DR|CT|LN|RD|WAY|CIR|TER|HWY|NE|SE|NW|SW)[A-Za-z]+)*\\b"
type_regex <- "\\b(?:ST|AVE|BLVD|DR|CT|LN|RD|WAY|CIR|PL|TER|HWY)\\b"
direction_regex <- "\\b(?:N|S|E|W|NE|SE|NW|SW)\\b"

# Extract each component and add the value as a new column
Raw_data['StreetNumber'] <- str_extract(Raw_data$Address1, number_regex)
Raw_data <- Raw_data %>% relocate(StreetNumber, .before = City)

Raw_data['StreetName'] <- str_extract(Raw_data$Address1, street_regex)
Raw_data <- Raw_data %>% relocate(StreetName, .before = City)

Raw_data['StreetType'] <- str_extract(Raw_data$Address1, type_regex)
Raw_data <- Raw_data %>% relocate(StreetType, .before = City)

Raw_data['StreetDirection'] <- str_extract(Raw_data$Address1, direction_regex)
Raw_data <- Raw_data %>% relocate(StreetDirection, .before = City)

# Convert StreetName and StreetType back to title case to correct grammar
Raw_data$StreetName <- str_to_title(Raw_data$StreetName)
Raw_data$StreetType <- str_to_title(Raw_data$StreetType)

# Set the value of Address2 equal to the form
# "StreetNumber" "StreetName" "StreetType" "Direction" "City", "State" "Zipcode"

# Create a new data frame to combine all columns while omitting NA values.
AddressPart1 <- data.frame(Raw_data$StreetNumber, Raw_data$StreetName, Raw_data$StreetType, Raw_data$StreetDirection)
AddressPart1$FullAddress <- apply(AddressPart1, 1, function(x) paste(x[!is.na(x)], collapse = " "))

# Reassign the combined address to Address2 in Raw_data and then past in the city, state and zip with commas
Raw_data$Address2 <- AddressPart1$FullAddress
Raw_data$Address2 <- paste(Raw_data$Address2, ", ", Raw_data$City, ", ", Raw_data$State, Raw_data$Zip)
Raw_data <- Raw_data %>% rename('FullAddress' = 'Address2')
Raw_data$StreetName <- AddressPart1$FullAddress

# Create a new data frame to geocode the address information
Raw_Geo_data <- data.frame(AddressPart1$FullAddress, Raw_data$City, Raw_data$State, Raw_data$Zip)

# Remove all the redundant data fields created in cleaning this portion of the data
Raw_data <- Raw_data %>% select(-StreetNumber, -StreetType, -StreetDirection, -Address1)
rm(AddressPart1)

# Export the cleaned data to CSV files in the data folder
write.csv(Raw_Geo_data, "Data/Data for export to Geocodio.csv", row.names=FALSE)
write.csv(Raw_data, "Data/Raw data (pre-geocoding).csv", row.names=FALSE)
}
```

```{r create final data set}
if(!file.exists("Data/Geolocated Data - Sales & Prospect - 5.11.2023.csv")) {
  
# Load the previously created csv files in preparation for merging
Temp_data <- read.csv("Data/Geocoded Addresses.csv")
Pre_Geo <- read.csv("Data/Raw data (pre-geocoding).csv")

# Remove unneeded columns from geo-data
Temp_data <- Temp_data[-c(2:5,10:19)]

# Combine the two data sets and save to file
Comb_data <- cbind(Pre_Geo, Temp_data[c("Latitude", "Longitude", "Accuracy.Score", "Accuracy.Type")])
write.csv(Comb_data, "Data/Geolocated Data - Sales & Prospect - 5.11.2023.csv", row.names=FALSE)
}
```

```{r register google API}
# GOOGELE_API KEY: AIzaSyAP8DfNNEAWuwN8aa2Ew_TopWR1rPLlSC4
ggmap::register_google(key="AIzaSyAP8DfNNEAWuwN8aa2Ew_TopWR1rPLlSC4")
```

```{r create datasets for mapping}
Data <- read.csv("Data/Geolocated Data - Sales & Prospect - 5.11.2023.csv")

# Remove all data fields taht do not have a contract date
Sales <- subset(Data, (!is.na(Data$ContractDate)))
Prospect <- subset(Data, (is.na(Data$ContractDate)))

# Remove all data points with a negative sale value
Sales <- Sales[Sales$GrossAmount >= 0,]

# Isolate each city into its own dataframe
ABQ_sales <- subset(Sales, Sales$City == "Albuquerque")
RR_sales <- subset(Sales, Sales$City == "Rio Rancho")
SF_sales <- subset(Sales, Sales$City == "Santa Fe")

# Combine the ABW and RR data into a single Metro area
Metro_sales <- dplyr::bind_rows(ABQ_sales, RR_sales)
```

```{r Adjust formatting for dates}
Sales$ContractDate <- mdy(Sales$ContractDate)
Metro_sales$ContractDate <- mdy(Metro_sales$ContractDate)
SF_sales$ContractDate <- mdy(SF_sales$ContractDate)
RR_sales$ContractDate <- mdy(RR_sales$ContractDate)
ABQ_sales$ContractDate <- mdy(ABQ_sales$ContractDate)
Prospect$DateAdded <- mdy(Prospect$DateAdded)
```

```{r create product categories}
# Create sub categories for each type of product in a city
ABQ_PC_sales <- subset(ABQ_sales, ABQ_sales$productid == "PC")
ABQ_Bath_sales <- subset(ABQ_sales, ABQ_sales$productid == "Bath")
ABQ_Sun_sales <- subset(ABQ_sales, ABQ_sales$productid == "Sun")
ABQ_Kitchen_sales <- subset(ABQ_sales, ABQ_sales$productid == "Kitchen")
ABQ_Win_sales <- subset(ABQ_sales, ABQ_sales$productid == "Win")

RR_PC_sales <- subset(RR_sales, RR_sales$productid == "PC")
RR_Bath_sales <- subset(RR_sales, RR_sales$productid == "Bath")
RR_Sun_sales <- subset(RR_sales, RR_sales$productid == "Sun")
RR_Kitchen_sales <- subset(RR_sales, RR_sales$productid == "Kitchen")
RR_Win_sales <- subset(RR_sales, RR_sales$productid == "Win")

SF_PC_sales <- subset(SF_sales, SF_sales$productid == "PC")
SF_Bath_sales <- subset(SF_sales, SF_sales$productid == "Bath")
SF_Sun_sales <- subset(SF_sales, SF_sales$productid == "Sun")
SF_Kitchen_sales <- subset(SF_sales, SF_sales$productid == "Kitchen")
SF_Win_sales <- subset(SF_sales, SF_sales$productid == "Win")

Metro_PC_sales <- subset(Metro_sales, Metro_sales$productid == "PC")
Metro_Bath_sales <- subset(Metro_sales, Metro_sales$productid == "Bath")
Metro_Sun_sales <- subset(Metro_sales, Metro_sales$productid == "Sun")
Metro_Kitchen_sales <- subset(Metro_sales, Metro_sales$productid == "Kitchen")
Metro_Win_sales <- subset(Metro_sales, Metro_sales$productid == "Win")

```

```{r distance function}
earth.dist <- function (long1, lat1, long2, lat2) {
  rad <- pi/180
  a1 <- lat1 * rad
  a2 <- long2 * rad
  b1 <- lat2 * rad
  b2 <- long2 * rad
  dlon <- b2 - a2
  dlat <- b1 - a1
  
  a <- (sin(dlat/2))^2 + cos(a1) * cos(b1) * (sin(dlon/2))^2
  c <- 2 * atan2(sqrt(a), sqrt(1 - a))
  R <-6378.145
  d <- R * c
  return(d)
}
```

```{r remove outliers for RR Data}
# Add empty column to each set of sales/prospect data
RR_sales['Distance'] <- NA
ABQ_sales['Distance'] <- NA
SF_sales['Distance'] <- NA

# Calculate distance from the calculated center of each area
RR_sales$Distance <- earth.dist(RR_sales$Longitude,
                                RR_sales$Latitude,
                                mean(RR_sales$Longitude),
                                mean(RR_sales$Latitude))
ABQ_sales$Distance <- earth.dist(ABQ_sales$Longitude,
                                ABQ_sales$Latitude,
                                mean(ABQ_sales$Longitude),
                                mean(ABQ_sales$Latitude))
SF_sales$Distance <- earth.dist(SF_sales$Longitude,
                                SF_sales$Latitude,
                                mean(SF_sales$Longitude),
                                mean(SF_sales$Latitude))

# Filter results farther than X miles from the center of the area
RR_sales <- RR_sales[RR_sales$Distance <= 10,] 
ABQ_sales <- ABQ_sales[ABQ_sales$Distance <= 15,]
SF_sales <- SF_sales[SF_sales$Distance <= 20,]
```

```{r fetch and save maps for future use}

if (!file.exists("Maps/NM_map.RData")){
NM <- ggmap(get_googlemap(center = c(lon = -106.018066, lat =34.307144),
                          zoom = 7, scale = 2, 
                          maptype = 'roadmap', 
                          color = 'bw'))
save(NM, file = "Maps/NM_map.RData")
}

if (!file.exists("Maps/Metro_map.RData")){
Metro <- ggmap(get_googlemap(center = c(lon = mean(Metro_sales$Longitude), mean(Metro_sales$Latitude)),
                          zoom = 11, scale = 1, 
                          maptype = 'roadmap', 
                          color = 'bw'))
save(Metro, file = "Maps/Metro_map.RData")
}

if (!file.exists("Maps/RR_map.RData")){
RR <- ggmap(get_googlemap(center = c(lon = mean(RR_sales$Longitude), mean(RR_sales$Latitude)),
                          zoom = 12, scale = 1, 
                          maptype = 'roadmap', 
                          color = 'bw'))
save(RR, file = "Maps/RR_map.RData")
}

if (!file.exists("Maps/SFcounty_map.RData")){
SFcounty <- ggmap(get_googlemap(center = c(lon = mean(SF_sales$Longitude), mean(SF_sales$Latitude)),
                          zoom = 11, scale = 1, 
                          maptype = 'roadmap', 
                          color = 'bw'))
save(SFcounty, file = "Maps/SFcounty_map.RData")
}

if (!file.exists("Maps/SF_map.RData")){
SF <- ggmap(get_googlemap(center = c(lon = mean(SF_sales$Longitude), mean(SF_sales$Latitude)),
                          zoom = 12, scale = 1, 
                          maptype = 'roadmap', 
                          color = 'bw'))
save(SF, file = "Maps/SF_map.RData")
}
```

```{r load maps from file}
load(file = "Maps/Metro_map.RData")
load(file = "Maps/NM_map.RData")
load(file = "Maps/RR_map.RData")
load(file = "Maps/SF_map.RData")
load(file = "Maps/SFcounty_map.RData")
```

```{r compute statistics for each city, include=FALSE}
# Stats for SF
SF_sales_by_zip <- SF_sales %>%
  group_by(Zip) %>%
  summarize(
    count = n(),
    med_Amount = median(GrossAmount),
    med_lat = mean(Latitude),
    med_long = mean(Longitude)
  )

SF_sales_by_zip %>%
  arrange(-count)

show(SF_sales_by_zip)

# Stats for ABQ
ABQ_sales_by_zip <- ABQ_sales %>%
  group_by(Zip) %>%
  summarize(
    count = n(),
    med_Amount = median(GrossAmount),
    med_lat = mean(Latitude),
    med_long = mean(Longitude)
  )

ABQ_sales_by_zip %>%
  arrange(-count)

show(ABQ_sales_by_zip)

# Stats for RR
RR_sales_by_zip <- RR_sales %>%
  group_by(Zip) %>%
  summarize(
    count = n(),
    med_Amount = median(GrossAmount),
    med_lat = mean(Latitude),
    med_long = mean(Longitude)
  )

RR_sales_by_zip %>%
  arrange(-count)

show(RR_sales_by_zip)
     
# Stats for Metro
Metro_sales_by_zip <- Metro_sales %>%
  group_by(Zip) %>%
  summarize(
    count = n(),
    med_Amount = median(GrossAmount),
    med_lat = mean(Latitude),
    med_long = mean(Longitude)
  )

Metro_sales_by_zip %>%
  arrange(-count)

show(Metro_sales_by_zip)

# Stats for Sales
Sales_by_zip <- Sales %>%
  group_by(Zip) %>%
  summarize(
    count = n(),
    med_Amount = median(GrossAmount),
    med_lat = mean(Latitude),
    med_long = mean(Longitude)
  )

Sales_by_zip %>%
  arrange(-count)

show(Sales_by_zip)

# Stats for Prospect
Prospect_by_zip <- Prospect %>%
  group_by(Zip) %>%
  summarize(
    count = n(),
    med_lat = mean(Latitude),
    med_long = mean(Longitude)
  )

Prospect_by_zip %>%
  arrange(-count)

show(Prospect_by_zip)

```

```{r test for maps}
# Santa Fe Sales
show(SF_sales_by_zip)

SF +
  geom_pointdensity(aes(x = Longitude,
                    y = Latitude),
                    data = SF_sales,
                    size = 1,
                    adjust = .05) +
  scale_color_viridis() +
  ggtitle("Santa Fe Total Sales")

SF +
  geom_pointdensity(aes(x = Longitude,
                    y = Latitude),
                    data = SF_PC_sales,
                    size = 1,
                    adjust = .05) +
  scale_color_viridis() +
  ggtitle("Santa Fe Patio Cover Sales")

SF +
  geom_pointdensity(aes(x = Longitude,
                    y = Latitude),
                    data = SF_Sun_sales,
                    size = 1,
                    adjust = .05) +
  scale_color_viridis() +
  ggtitle("Santa Fe Sunroom Sales")

SF +
  geom_pointdensity(aes(x = Longitude,
                    y = Latitude),
                    data = SF_Bath_sales,
                    size = 1,
                    adjust = .05) +
  scale_color_viridis() +
  ggtitle("Santa Fe Bath Sales")

SF +
  geom_pointdensity(aes(x = Longitude,
                    y = Latitude),
                    data = SF_Kitchen_sales,
                    size = 1,
                    adjust = .05) +
  scale_color_viridis() +
  ggtitle("Santa Fe Kitchen Sales")

SF +
  geom_pointdensity(aes(x = Longitude,
                    y = Latitude),
                    data = SF_Win_sales,
                    size = 1,
                    adjust = .05) +
  scale_color_viridis() +
  ggtitle("Santa Fe Window Sales")

# Rio Rancho Sales
show(RR_sales_by_zip)

RR + 
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = RR_sales,
                    size = 1,
                    adjust = .01) +
  scale_color_viridis() +
  ggtitle("Rio Rancho Total Sales")

RR + 
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = RR_PC_sales,
                    size = 1,
                    adjust = .01) +
  scale_color_viridis() +
  ggtitle("Rio Rancho Pation Cover Sales")

RR + 
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = RR_Sun_sales,
                    size = 1,
                    adjust = .01) +
  scale_color_viridis() +
  ggtitle("Rio Rancho Sunroom Sales")

RR + 
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = RR_Bath_sales,
                    size = 1,
                    adjust = .01) +
  scale_color_viridis() +
  ggtitle("Rio Rancho Bath Sales")

RR + 
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = RR_Kitchen_sales,
                    size = 1,
                    adjust = .01) +
  scale_color_viridis() +
  ggtitle("Rio Rancho Kitchen Sales")

RR + 
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = RR_Win_sales,
                    size = 1,
                    adjust = .01) +
  scale_color_viridis() +
  ggtitle("Rio Rancho Window Sales")

# Metro Sales
show(Metro_sales_by_zip)

Metro +
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = Metro_sales,
                    size = .5,
                    adjust = .01) +
  scale_color_viridis() +
  ggtitle("Metro Area Total Sales")

Metro +
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = Metro_PC_sales,
                    size = .5,
                    adjust = .01)+
  scale_color_viridis() +
  ggtitle("Metro Area Patio Cover Sales")

Metro +
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = Metro_Sun_sales,
                    size = .5,
                    adjust = .01)+
  scale_color_viridis() +
  ggtitle("Metro Area Sunrooom Sales")

Metro +
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = Metro_Bath_sales,
                    size = .5,
                    adjust = .01)+
  scale_color_viridis() +
  ggtitle("Metro Area Bath Sales")

Metro +
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = Metro_Kitchen_sales,
                    size = .5,
                    adjust = .01)+
  scale_color_viridis() +
  ggtitle("Metro Area Kitchen Sales")

Metro +
  geom_pointdensity(aes(x = Longitude, y = Latitude),
                    data = Metro_Win_sales,
                    size = .5,
                    adjust = .01)+
  scale_color_viridis() +
  ggtitle("Metro Area Window Sales")
```

```{r break out specific products}
p1 = calendarHeat(
  Sales$ContractDate,
  Sales$GrossAmount,
  color = 'r2b',
  ncolors = 25,
  varname = "Historic Sales Seasonality"
)

st(Sales,title = 'Overall Sales',
   vars = c('GrossAmount', 'Latitude', 'Longitude'))

st(ABQ_sales,title = 'Albuquerque Sales',
   vars = c('GrossAmount', 'Latitude', 'Longitude'))

st(RR_sales,title = 'Rio Rancho Sales',
   vars = c('GrossAmount', 'Latitude', 'Longitude'))

st(SF_sales,title = 'Metro Area Sales',
   vars = c('GrossAmount', 'Latitude', 'Longitude'))

st(SF_sales_by_zip,title = 'Santa Fe Sales',
   vars = c('GrossAmount', 'Latitude', 'Longtitude'))
```

```{r timeseries}
#devtools::install_github('Ather-Energy/ggTimeSeries')

time <- ggplot(ABQ_PC_sales, aes(x=ContractDate, y=GrossAmount)) +
  geom_line() + 
  geom_smooth(method = lm, se = FALSE, size = 1.5) +
  xlab("") +
  ggtitle("Albuquerque PC Sales")
time
```

```{r citation}
citation("ggmap")
sessionInfo()
```
